export enum RefundType {
  FULLY_REFUNDABLE = 'FULLY_REFUNDABLE',
  PARTLY_REFUNDABLE = 'PARTLY_REFUNDABLE',
  VARIBALE_REFUND = 'VARIBALE_REFUND',
}

export enum RefundAmountType {
  CONSTANT_AMOUNT = 'CONSTANT_AMOUNT',
  CONSTANT_PERCENTAGE = 'CONSTANT_PERCENTAGE',
  VARIBALE_AMOUNT = 'VARIBALE_AMOUNT',
  VARIBALE_PERCENTAGE = 'VARIBALE_PERCENTAGE',
}
